// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6q79De_1sd5fHQ88jewkDVUISw3u8Jgk',
    appId: '1:919876240633:web:829c0606b96392ee92ce28',
    messagingSenderId: '919876240633',
    projectId: 'book-swap-app-21029',
    authDomain: 'book-swap-app-21029.firebaseapp.com',
    storageBucket: 'book-swap-app-21029.firebasestorage.app',
    measurementId: 'G-8EW0C6896L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt1T5uLfaZr-Q9t0Z-Vzv8PeL8GbqbsgY',
    appId: '1:919876240633:android:83644630d7fb781d92ce28',
    messagingSenderId: '919876240633',
    projectId: 'book-swap-app-21029',
    storageBucket: 'book-swap-app-21029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2snSTX53nuZvjbRyraCly4ChA9-wZsv4',
    appId: '1:919876240633:ios:a51170672152356c92ce28',
    messagingSenderId: '919876240633',
    projectId: 'book-swap-app-21029',
    storageBucket: 'book-swap-app-21029.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2snSTX53nuZvjbRyraCly4ChA9-wZsv4',
    appId: '1:919876240633:ios:a51170672152356c92ce28',
    messagingSenderId: '919876240633',
    projectId: 'book-swap-app-21029',
    storageBucket: 'book-swap-app-21029.firebasestorage.app',
    iosBundleId: 'com.example.bookSwapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6q79De_1sd5fHQ88jewkDVUISw3u8Jgk',
    appId: '1:919876240633:web:c730b25c6d3e070b92ce28',
    messagingSenderId: '919876240633',
    projectId: 'book-swap-app-21029',
    authDomain: 'book-swap-app-21029.firebaseapp.com',
    storageBucket: 'book-swap-app-21029.firebasestorage.app',
    measurementId: 'G-HC0DMCF26C',
  );
}
